name: wifi_hunter
description: A flutter package to hunt down info from all WiFi APs around you.
version: 1.0.2
homepage: https://github.com/Klingens13/wifi_hunter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    androidPackage: klingens13.wifi_hunter
    pluginClass: WiFiHunterPlugin


